auth_system/urls.py
from django.urls import path
import auth_system.views as views

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("log-out/", views.CustomLogoutView.as_view(), name="log-out"),
    path("register/", views.RegisterView.as_view(), name="register"),
]

app_name = "auth_system"

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tracking.urls")),
    path('', include('auth_system.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracking/urls.py
from django.urls import path
from tracking import views

urlpatterns = [
    path('', views.home_page, name="home"),
    path('tasks/', views.TasksListView.as_view(), name="task-list"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-detail"),
    path('add-task/', views.TaskCreateView.as_view(), name="add-task"),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name="update-task"),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name="delete-task"),
    path('<int:pk>/complete/', views.TaskCompleteView.as_view(), name="task-complete"),
    path('<int:pk>/update-comment/', views.CommentUpdateView.as_view(), name="update-comment"),
    path('<int:pk>/delete-comment/', views.CommentDeleteView.as_view(), name="delete-comment"),
    path('comment/like/<int:pk>/', views.CommentLikeToggle.as_view(), name='comment-like-toggle'),
    path("user/<int:pk>/", views.UserPageView.as_view(), name="user-page"),
    path("user/<int:pk>/tasks/", views.UserTasksListView.as_view(), name="user-tasks"),
    path("user-update/<int:pk>/", views.UpdateUserView.as_view(), name="update-user"),
    path("subscribe/<int:pk>/", views.SurbscribeUserView.as_view(), name="subscribe"),
    path('user/<int:pk>/subscribers/', views.UserSubscribersView.as_view(), name='user-subscribers'),
    path('user/<int:pk>/subscribers-to/', views.UserSubscribersToView.as_view(), name='user-subscribers-to'),

]

app_name = "tasks"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Tasking</title>
</head>
<body style="background-color: #ededed">
        <nav class="sticky-top nav-shadow">
      <div class= "row">
        <div class = 'col-md-1'>
            <img src="{% static './images/base/site-icon.png' %}" class = "img-icon-nav">
        </div>
        <div class = 'col-md-1'>
          <a href = "{% url 'tasks:home' %}" class="a-nav">Home</a>
        </div>
        <div class = 'col-md-1'>
          <a href = "{% url 'tasks:task-list' %}" class="a-nav">Tasks</a>
        </div>
        <div class="col-md-1">
            <a href = "{% url 'tasks:add-task' %}" class="a-nav">Add task</a>
        </div>
        {% if request.user.is_authenticated %}
            <div class="col-md-5"></div>
          <div class="col-md-1">
              <form method="post" action="{% url 'tasks:log-out' %}">
                {% csrf_token %}
                <button type="submit" class="a-nav-log-out ">Log out</button>
            </form>
          </div>
            <div class = 'col-md-1'>
                <a href = "{% url 'tasks:user-page' request.user.pk %}" class="a-nav-user">Профіль</a>
            </div>
            <div class = 'col-md-1'>
                <img src="{% static './images/base/user-icon.png' %}" class = "img-icon-nav">
            </div>
            {% else %}
                <div class="col-md-6"></div>
                <div class = 'col-md-1'>
                    <a href = "{% url 'tasks:login' %}" class="a-nav" id="my_kabinet">Log in</a>
                </div>
                <div class = 'col-md-1'>
                    <a href = "{% url 'tasks:register' %}" class="a-nav">Register</a>
                </div>
            {% endif %}
        </div>

    </nav>
    <!--<div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <br>
            <div class="main-background">-->
                {% block content %}
                {% endblock %}
            <!--</div>
            <br>
        </div>
        <div class="col-md-1"></div>
    </div>-->
    <script src="{% static './js/tasks.js' %}" ></script>
</body>
</html>