system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tracking.urls")),
    path('', include('auth_system.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracking/urls.py
from django.urls import path
from tracking import views

urlpatterns = [
    path('', views.home_page, name="home"),
    path('tasks/', views.TasksListView.as_view(), name="task-list"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-detail"),
    path('add-task/', views.TaskCreateView.as_view(), name="add-task"),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name="update-task"),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name="delete-task"),
    path('<int:pk>/complete/', views.TaskCompleteView.as_view(), name="task-complete"),
    path('<int:pk>/update-comment/', views.CommentUpdateView.as_view(), name="update-comment"),
    path('<int:pk>/delete-comment/', views.CommentDeleteView.as_view(), name="delete-comment"),
    path('comment/like/<int:pk>/', views.CommentLikeToggle.as_view(), name='comment-like-toggle'),
    path("user/<int:pk>/", views.UserPageView.as_view(), name="user-page"),
    path("user/<int:pk>/tasks/", views.UserTasksListView.as_view(), name="user-tasks"),
    path("user-update/<int:pk>/", views.UpdateUserView.as_view(), name="update-user"),
    path("subscribe/<int:pk>/", views.SurbscribeUserView.as_view(), name="subscribe"),
    path('user/<int:pk>/subscribers/', views.UserSubscribersView.as_view(), name='user-subscribers'),
    path('user/<int:pk>/subscribers-to/', views.UserSubscribersToView.as_view(), name='user-subscribers-to'),

]

app_name = "tasks"

templates/tasks/comment-delete-confirmation.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2>Видалення коменту</h2>
    <p>Ви впевнені, що хочете видалити комент?</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Так, видалити</button>
        <a href="{% url 'tasks:task-detail' comment.task.pk %}" class="btn btn-secondary">Ні, повернутися до завдання</a>
    </form>
</div>

{% endblock %}

templates/tasks/comment_update.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-3">
    <h2>Оновлення коменту</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Оновити комент</button>
        <a href="{% url 'tasks:task-detail' comment.task.pk %}" class="btn btn-secondary">Назад до завдання</a>
    </form>
</div>

{% endblock %}

templates/tasks/login.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <br>
        <br>
        <br>
        <br>
        <br>
        <div class="main-background">
            <h2 style="text-align: center; font: 600 'Source Sans Pro', sans-serif; ">Log in</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="row">
                    <div class="col-3"></div>
                    <div class="col-8">
                        <button type="submit" class="btn btn-primary btn-log-in">Login</button>
                    </div>
                    <div class="col-1"></div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

templates/tasks/register.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">

        <br>
        <br>
        <div class="main-background">
            <h2 style="text-align: center; font: 600 'Source Sans Pro', sans-serif; ">Register</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-8">
                        <button type="submit" class="btn btn-success btn-register">Register</button>
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </form>
        </div>
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

templates/tasks/subscribes-to.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <br>
        {% for subscribe in subscribes %}
            <div class="main-background">
                <a class="a-comment-user-name" href = "{% url 'tasks:user-page' subscribe.user.pk %}"><img src="{% static './images/task-detail/user.png' %}" class="img-task-priority"> {{ subscribe.user.first_name }} {{ subscribe.user.last_name }}</a>
            </div>
            <br>
        {% endfor %}
        <br>
    </div>
    <div class="col-md-4"></div>
</div>

{% endblock %}

templates/tasks/subscribes.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <br>
        {% for subscribe in subscribes %}
            <div class="main-background">
                <a class="a-comment-user-name" href = "{% url 'tasks:user-page' subscribe.subscriber.pk %}"><img src="{% static './images/task-detail/user.png' %}" class="img-task-priority"> {{ subscribe.subscriber.first_name }} {{ subscribe.subscriber.last_name }}</a>
            </div>
            <br>
        {% endfor %}
        <br>
    </div>
    <div class="col-md-4"></div>
</div>


{% endblock %}

templates/tasks/task-creating.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <br>
        <div class="main-background">
            <div class="container mt-3">
                <h2 style="font: 600 'Source Sans Pro', sans-serif; text-align:center;">Add task</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-success btn-log-in">Save</button>
                        </div>
                        <div class="col-md-4"></div>
                    </div>
                </form>
            </div>
        </div>
        <br>
    </div>
    <div class="col-md-3"></div>
</div>

{% endblock %}

templates/tasks/task-delete-confirmation.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2>Видалення завдання</h2>
    <p>Ви впевнені, що хочете видалити завдання "{{ task.name }}"</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Так, видалити</button>
        <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary">Ні, повернутися до списку завдань</a>
    </form>
</div>

{% endblock %}

templates/tasks/task-detail.html
{% extends 'base.html' %}

{% block content %}
{% load custom_tags %}
{% load static %}
<div class = "row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <br>
            <div class="row">
                <div class="col-md-7">
                    <div class="main-background">
                        <h1 class="task-name-detail" >{{ task.name }}</h1>
                        <div class="imgs-priority-status">
                            {% if task.priority == "high" %}
                                <img src="{% static './images/task-list/high-priority.png' %}" class="img-task-priority">
                            {% elif task.priority == "medium" %}
                                <img src="{% static './images/task-list/medium-priority.png' %}"  class="img-task-priority">
                            {% elif task.priority == "low" %}
                                <img src="{% static './images/task-list/low-priority.png' %}" class="img-task-priority">
                            {%endif%}
                            {% if task.status == "done" %}
                                <img src="{% static './images/task-list/status-done.png' %}" class="img-task-priority">
                            {% elif task.status == "in_progress" %}
                                <img src="{% static './images/task-list/status-inprogress.png' %}" class="img-task-priority">
                            {% elif task.status == "todo" %}
                                <img src="{% static './images/task-list/status-todo.png' %}" class="img-task-priority">
                            {%endif%}
                        </div>
                        <div class="desc-detail-div">
                            <p class="desc-detail">{{ task.description }}</p>
                        </div>
                        <br>
                        <h6>{{ task.due_date }}</h6>
                        {% if request.user == task.user %}
                            <a href="{% url 'tasks:update-task' task.id %}" class="btn btn-warning">Редагувати</a>
                            <a href="{% url 'tasks:delete-task' task.id %}" class="btn btn-danger">Видалити</a>
                        {% endif %}
                        <hr>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="main-background">
                    <div class="comments-div " tabindex="0">
                        <div id="form-add-comment" style="display:none">
                        <div class="card card-comment">
                            <div class="row">
                                <div class="col-md-8">
                                    <a class="a-comment-user-name" href = "#"><img src="{% static './images/task-detail/user.png' %}" class="img-task-priority"> {{ request.user.first_name }} {{ request.user.last_name }}</a>
                                </div>
                                <div class="col-md-4">
                                    <div style="text-align: right;">
                                        <a><img src="{% static './images/task-detail/edit-comment.png' %}" class="img-task-priority"></a>
                                        <a><img src="{% static './images/task-detail/delete-comment.png' %}" class="img-task-priority"></a>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <form action="{% url 'tasks:task-detail' task.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <p style="font: 600 'Source Sans Pro', sans-serif;">{{ comment_form.text }}</p>
                                <hr>
                                <div class="comment-media">
                                    {{ comment_form.media }}
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8">
                                        <button type="submit" class="btn btn-primary btn-adding">Add</button>
                                    </div>
                                    <div class="col-md-2"></div>
                                </div>
                            </form>
                            <hr>
                            <div class="row">
                                <div class="col-md-8">
                                    <h6 class="time-comment">Date</h6>
                                </div>
                                <div class="col-md-4">
                                    <form>
                                        {% csrf_token %}
                                        <button type="submit" class="btn-like">
                                            <img src="{% static './images/task-detail/like.png' %}" class="img-task-priority">0
                                        </button>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <br>
                        </div>
                    {% for comment in comments %}
                        <div class="card card-comment">
                            <div class="row">
                                <div class="col-md-8">
                                    <a class="a-comment-user-name" href = "{% url 'tasks:user-page' comment.user.pk %}"><img src="{% static './images/task-detail/user.png' %}" class="img-task-priority"> {{ comment.user.first_name }} {{ comment.user.last_name }}</a>
                                </div>
                                <div class="col-md-4">
                                    <div style="text-align: right;">
                                        {% if request.user == comment.user %}
                                            <a href="{% url 'tasks:update-comment' comment.id %}"><img src="{% static './images/task-detail/edit-comment.png' %}" class="img-task-priority"></a>
                                            <a href="{% url 'tasks:delete-comment' comment.id %}"><img src="{% static './images/task-detail/delete-comment.png' %}" class="img-task-priority"></a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <p style="font: 600 'Source Sans Pro', sans-serif;">{{ comment.text }}</p>
                            <hr>
                            {% if comment.media %}
                                <div class="comment-media">
                                    {% if comment.media.url|endswith:".jpg" or comment.media.url|endswith:".png" or comment.media.url|endswith:".jpeg" or comment.media.url|endswith:".webp" %}
                                        <img src="{{ comment.media.url }}" alt="Зображення коментаря" class="img-comment">
                                    {% elif comment.media.url|endswith:".mp4" %}
                                        <video class="img-comment" controls>
                                            <source src="{{ comment.media.url }}" type="video/mp4">
                                            Your browser does not support the video tag.
                                        </video>
                                    {% else %}
                                        <a href="{{ comment.media.url }}">Завантажити файл</a>
                                    {% endif %}
                                </div>
                            <hr>
                            {% endif %}
                            <div class="row">
                                <div class="col-md-8">
                                    <h6 class="time-comment">{{ comment.published_date }}</h6>
                                </div>
                                <div class="col-md-4">
                                    <form action="{% url 'tasks:comment-like-toggle' comment.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn-like">
                                            <img src="{% static './images/task-detail/like.png' %}" class="img-task-priority">{{ comment.likes.count }}
                                        </button>
                                    </form>
                                </div>
                            </div>

                        </div>
                        <br>
                    {% endfor %}
                    </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-5"></div>
                        <div class="col-md-4">
                            <button class = "button_add" onclick="show_add_comment()">+</button>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        <br>
        <div class="row">
            <div class = "col-md-5"></div>
            <div class = "col-md-2">

            </div>
            <div class = "col-md-5"></div>
        </div>
        <br>
                <br>
            </div>
            <br>
            <div class="row">
                <div class="col-md-5"></div>
                <div class="col-md-2">
                    <button class="button_hide_add" onclick="hide_add_comment()">×</button>
                </div>
                <div class="col-md-5"></div>
            </div>
        </div>
        <br>
    </div>
</div>
{% endblock %}

templates/tasks/task-list.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <br>
        <div class="main-background">
            <br>
            <div class="row">
                <div class="col-md-7">
                    <form method="get" class="form-inline mb-3">
                        {{ task_search_form.name }}
                        <button type="submit" class="btn-search"><img src="{% static './images/task-list/search-icon.png' %}" class="img-search"></button>
                    </form>
                </div>
                <div class="col-md-5">
                    <form method="get" class="form-inline mb-3">
                        {{ task_filter_form.status.label_tag }}
                        {{ task_filter_form.status }}
                        <br>
                        {{ task_filter_form.priority.label_tag }}
                        {{ task_filter_form.priority }}
                        <button type="submit" class="btn btn-primary ml-2">Фільтрувати</button>
                    </form>
                </div>
            </div>
<br>
    <div class="container">
        <div class="row">
            {% for task in tasks %}
            <div class="col-md-3">
                <a href = "{% url 'tasks:task-detail' task.id %}" class="a-task">
                <div class="card task-card">
                    <div class="row">
                        <div class = "col-md-8">
                            <!--<h4><a href = "{% url 'tasks:task-detail' task.id %}">{{ task.name }}</h4>-->
                            <h5 class="task-name">{{ task.name }}</h5>
                        </div>
                        <div class = "col-md-4">
                            <div class="icons-task-h5">
                                {% if task.priority == "high" %}
                                    <img src="{% static './images/task-list/high-priority.png' %}" class="img-task-priority">
                                {% elif task.priority == "medium" %}
                                    <img src="{% static './images/task-list/medium-priority.png' %}"  class="img-task-priority">
                                {% elif task.priority == "low" %}
                                    <img src="{% static './images/task-list/low-priority.png' %}" class="img-task-priority">
                                {%endif%}
                                {% if task.status == "done" %}
                                    <img src="{% static './images/task-list/status-done.png' %}" class="img-task-priority">
                                {% elif task.status == "in_progress" %}
                                    <img src="{% static './images/task-list/status-inprogress.png' %}" class="img-task-priority">
                                {% elif task.status == "todo" %}
                                    <img src="{% static './images/task-list/status-todo.png' %}" class="img-task-priority">
                                {%endif%}
                            </div>
                        </div>
                    </div>
                    <h6 class="due-date-task">
                        <img src="{% static './images/task-list/time.png' %}" class="img-task-priority"> {{ task.due_date }}
                    </h6>
                    <form action="{% url 'tasks:task-complete' task.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-warning btn-sm btn-done">Done</button>
                    </form>
                </div>
                </a>
                <br>
            </div>
            {% endfor %}
        </div>
    </div>
        </div>
        <br>
    </div>
    <div class="col-md-1"></div>
</div>
{% endblock %}

templates/tasks/task-updating.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-3">
    <h2>Оновлення задачі</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Оновити завдання</button>
        <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary">Назад до списку завдань</a>
    </form>
</div>

{% endblock %}

templates/tasks/update-user.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <br>
        <div class="main-background">
            <div class="container mt-3">
                <h2 style="text-align:center; font: 600 'Source Sans Pro', sans-serif;">Edit user</h2>
                <div>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-warning" >Edit</button>
                        <a href="{% url 'tasks:user-page' user.pk %}" class="btn btn-secondary">Back</a>
                    </form>
                </div>
            </div>
        </div>
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}

templates/tasks/user-page.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="main-background">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="user-name">{{ user.first_name }} {{ user.last_name }}</h1>
                    <hr>
                    <div class="row">
                        <div class="col-md-4">
                            <h5 class="user-dani">{{ user.tasks.count }}</h5>
                            <h5 style="text-align:center;"><a href = "{% url 'tasks:user-tasks' user.pk %}" class="user-dani-a">Tasks</a></h5>
                        </div>
                        <div class="col-md-4">
                            <h5 class="user-dani">{{ user.subscribes.count }}</h5>
                            <h5 style="text-align:center;"> <a href="{% url 'tasks:user-subscribers' user.pk %}" class="user-dani-a" >Subscribes</a></h5>
                        </div>
                        <div class="col-md-4">
                            <h5 class="user-dani">{{ user.subscribes_to.count }}</h5>
                            <h5 style="text-align:center;"><a href="{% url 'tasks:user-subscribers-to' user.pk %}" class="user-dani-a">Subscribe to</a></h5>
                        </div>
                    </div>
                    <br>
                    {% if request.user != user %}
                        <form action="{% url 'tasks:subscribe' user.pk %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-3"></div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary btn-subscribe">
                                        Subscribe
                                    </button>
                                </div>
                                <div class="col-md-5"></div>
                            </div>
                        </form>
                    {% endif %}
                    <hr>
                    {% if request.user == user %}
                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-4">
                                <a href="{% url 'tasks:update-user' user.pk %}" class="btn btn-warning btn-update-user">Edit</a>
                            </div>
                            <div class="col-md-5"></div>
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-5">
                    <img src="{% static './images/task-detail/user.png' %}" class="user-page-image" >
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

templates/tasks/user-tasks.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <br>
        {% for task in user_tasks %}
            <div class="main-background">
                <div class="row">
                    <div class="col-md-4">
                        <a class="a-comment-user-name" href = "{% url 'tasks:task-detail' task.pk %}" style="font-size: 24px">{{ task.name }}</a>
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <div class="imgs-priority-status">
                            {% if task.priority == "high" %}
                                <img src="{% static './images/task-list/high-priority.png' %}" class="img-task-priority">
                            {% elif task.priority == "medium" %}
                                <img src="{% static './images/task-list/medium-priority.png' %}"  class="img-task-priority">
                            {% elif task.priority == "low" %}
                                <img src="{% static './images/task-list/low-priority.png' %}" class="img-task-priority">
                            {%endif%}
                            {% if task.status == "done" %}
                                <img src="{% static './images/task-list/status-done.png' %}" class="img-task-priority">
                            {% elif task.status == "in_progress" %}
                                <img src="{% static './images/task-list/status-inprogress.png' %}" class="img-task-priority">
                            {% elif task.status == "todo" %}
                                <img src="{% static './images/task-list/status-todo.png' %}" class="img-task-priority">
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
        <br>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock %}